import fs from 'node:fs'
import { createRequire } from 'node:module'
import path from 'node:path'
import { buildSnapshot } from '../src/import/greenmarket-price/parse-workbook'

const projectRoot = path.resolve(import.meta.dirname, '..')
const importDir = path.join(projectRoot, 'data/import/greenmarket-price-v1')
const outputFile = path.join(projectRoot, 'src/catalog/generated-price-catalog.ts')

type SheetJs = {
  readFile: (
    filePath: string,
    options?: { cellDates?: boolean },
  ) => {
    SheetNames: string[]
    Sheets: Record<string, unknown>
  }
  utils: {
    sheet_to_json: (sheet: unknown, options: object) => unknown[][]
  }
}

function loadSheetJs(): SheetJs | null {
  try {
    const require = createRequire(import.meta.url)
    return require('xlsx') as SheetJs
  } catch {
    return null
  }
}

function resolveSourceFile() {
  if (!fs.existsSync(importDir)) {
    throw new Error(`Import directory not found: ${importDir}`)
  }

  const files = fs
    .readdirSync(importDir)
    .filter((name) => name.toLowerCase().endsWith('.xlsx') && !name.toLowerCase().includes('.bak.'))

  if (files.length === 0) {
    throw new Error(`No .xlsx files found in ${importDir}`)
  }

  if (files.length > 1) {
    const preferred = files.find((name) => name.includes('Прайс') && !name.toLowerCase().includes('.bak.'))

    if (preferred) {
      return path.join(importDir, preferred)
    }
  }

  return path.join(importDir, files[0]!)
}

function keepExistingCatalog(reason: string) {
  if (fs.existsSync(outputFile)) {
    console.log(`${reason}, keeping ${path.relative(projectRoot, outputFile)}`)
    return true
  }

  return false
}

function main() {
  if (!fs.existsSync(importDir)) {
    if (keepExistingCatalog('Import directory missing')) {
      return
    }

    throw new Error(`Import directory not found: ${importDir}`)
  }

  const files = fs
    .readdirSync(importDir)
    .filter((name) => name.toLowerCase().endsWith('.xlsx') && !name.toLowerCase().includes('.bak.'))

  if (files.length === 0) {
    if (keepExistingCatalog('No .xlsx in import directory')) {
      return
    }

    throw new Error(`No .xlsx files found in ${importDir}`)
  }

  const XLSX = loadSheetJs()

  if (!XLSX) {
    if (
      keepExistingCatalog(
        'SheetJS (xlsx) is not installed; regenerate locally with `npm i -D xlsx@0.18.5` then rerun',
      )
    ) {
      return
    }

    throw new Error(
      'SheetJS (xlsx) is required to generate the price catalog. Install locally: npm i -D xlsx@0.18.5',
    )
  }

  const sourceFile = resolveSourceFile()
  const workbook = XLSX.readFile(sourceFile, { cellDates: false })
  const sheetRows = new Map<string, unknown[][]>()

  for (const sheetName of workbook.SheetNames) {
    sheetRows.set(
      sheetName,
      XLSX.utils.sheet_to_json(workbook.Sheets[sheetName]!, {
        header: 1,
        defval: null,
      }),
    )
  }

  const snapshot = buildSnapshot({
    sourceFile: path.relative(projectRoot, sourceFile).replace(/\\/g, '/'),
    sheetNames: workbook.SheetNames,
    sheetRows,
  })

  const contents = `// Generated by scripts/build-price-catalog.ts — do not edit manually.
// Source: ${snapshot.sourceFile}
// Generated at: ${snapshot.generatedAt}

import type {
  PriceCatalogCategory,
  PriceCatalogGroup,
  PriceCatalogSnapshot,
} from '@/import/greenmarket-price/types'

export const priceCatalogSnapshot = ${JSON.stringify(snapshot, null, 2)} as const satisfies PriceCatalogSnapshot

export const catalogGroups: readonly PriceCatalogGroup[] = priceCatalogSnapshot.groups

export const catalogCategories: readonly PriceCatalogCategory[] = priceCatalogSnapshot.categories

export function getCategoryBySlug(slug: string) {
  return catalogCategories.find((category) => category.slug === slug)
}

export function getSubcategory(categorySlug: string, subcategorySlug: string) {
  const category = getCategoryBySlug(categorySlug)

  if (!category) {
    return null
  }

  const subcategory = category.subcategories.find((item) => item.slug === subcategorySlug)

  if (!subcategory) {
    return null
  }

  return { category, subcategory }
}

export function getProductById(productId: string) {
  for (const category of catalogCategories) {
    for (const subcategory of category.subcategories) {
      const product = subcategory.products.find((item) => item.id === productId)

      if (product) {
        return { category, subcategory, product }
      }
    }
  }

  return null
}

export function listProductIds() {
  return catalogCategories.flatMap((category) =>
    category.subcategories.flatMap((subcategory) => subcategory.products.map((product) => product.id)),
  )
}
`

  fs.mkdirSync(path.dirname(outputFile), { recursive: true })
  fs.writeFileSync(outputFile, contents, 'utf8')

  console.log(
    `Price catalog generated: ${snapshot.categories.length} categories, ${snapshot.productCount} products -> ${path.relative(projectRoot, outputFile)}`,
  )
}

main()
